### ISSUE TITLE
Many RuntimeWarnings

### ISSUE THREAD

**Issue by petrvanblokland** [LettError/similarity#3]
Using this code line, many RuntimeWarnings show:

result = SimilarityRepresentationFactory(f['A'], sameUnicodeClass=False, sameUnicodeRange=False, threshold=0.9)

scriptsLib/cosineSimilarity.py:176: RuntimeWarning: invalid value encountered in double_scalars
scriptsLib/cosineSimilarity.py:176: RuntimeWarning: invalid value encountered in double_scalars
scriptsLib/cosineSimilarity.py:176: RuntimeWarning: invalid value encountered in double_scalars
scriptsLib/cosineSimilarity.py:176: RuntimeWarning: invalid value encountered in double_scalars
scriptsLib/cosineSimilarity.py:176: RuntimeWarning: invalid value encountered in double_scalars

**Comment by LettError** [comment]
Mute all numpy warnings while we're doing math. 
[    old_settings = numpy.seterr(all='ignore')  #seterr to known value](https://github.com/LettError/similarity/blob/b9f25a5e9261a9dd26631763fa349cd8569c503b/lib/cosineSimilarity.py#L176)
